name: Labeler

on:
  pull_request_target:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: fregante/title-to-labels-action@v1
        with:
          token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: fregante/keyword-formatter-action@v1
        with:
          token: ${{ github.token }}
          keywords-path: source/features
